package configs

import "time"

const (
	// Session Rules
	SESSION_DURATION = 30 * 24 * time.Hour

	// Restaurant Rules
	BASIC_MAX_RESTAURANT_COUNT   = 1
	PRO_MAX_RESTAURANT_COUNT     = 5
	PREMIUM_MAX_RESTAURANT_COUNT = 10

	// Menu Rules
	BASIC_MAX_MENU_COUNT       = 1
	BASIC_ALLOWED_MENU_TYPES   = 5
	PRO_MAX_MENU_COUNT         = 5
	PRO_ALLOWED_MENU_TYPES     = 10
	PREMIUM_MAX_MENU_COUNT     = 10
	PREMIUM_ALLOWED_MENU_TYPES = 20

	// Image Rules
	BASIC_ALLOWED_IMAGE    = 10
	BASIC_MAX_IMAGE_SIZE   = 5 * 1024 * 1024
	PRO_ALLOWED_IMAGE      = 100
	PRO_MAX_IMAGE_SIZE     = 10 * 1024 * 1024
	PREMIUM_ALLOWED_IMAGE  = 250
	PREMIUM_MAX_IMAGE_SIZE = 20 * 1024 * 1024
)
